### ISSUE TITLE
Error in read_tags: Expected content type application/json, not text/html

### ISSUE THREAD

**Issue by lfagliano** [ropensci/tidytags#61]
Hi all!

Thanks for the package!

I am having a problem with read_tags. I followed all the vignette explanations, but when I am running read_tags it gives me:

tags_ukraine_es_url <- read_tags("https://docs.google.com/spreadsheets/d/1eWQKccB0Qnqk0io9jhJI4muIri0s3l_HYYtlZfbg7Do/edit?usp=sharing")
Error: Expected content type application/json, not text/html.
* <!DOCTYPE html> <html lang=en> <meta charset=utf-8> <meta name=viewport content="initial-scale=1, minimum-scale=1,
  width=device-width"> <title>Error 502 (Server Error)!!1</title> <style> ...

The file is huge, don't know if that could be the issue.

**Comment by bretsw** [comment]
Hi @lfagliano, thank you for alerting me to this! When I replicated your code, I got the same error. Note that the beginning part of the error message is especially useful: 

>Error in `gargle_abort_request_failed()`:

This makes me think the issue is related to something in the **gargle** package (which is essential for **googlesheets4**, which underlies `read_tags()`. 

I did some digging, and it seems a number of **googlesheets4** or **googledrive** package users have encountered related errors:
- https://github.com/tidyverse/googledrive/issues/234
- https://github.com/tidyverse/googlesheets4/issues/110
- https://github.com/tidyverse/googlesheets4/issues/155
- https://github.com/tidyverse/googlesheets4/issues/187

The common thread I see across these past errors is the size of Google Sheet (in your case, the TAGS spreadsheet has more 550,000 rows!). My guess is that this huge amount of data is messing with the Google Sheets API or even an internet connectivity issue.

Start by trying the two recommendations in this specific comment:
- https://github.com/tidyverse/googlesheets4/issues/155#issuecomment-629497403

See where that gets you. Otherwise, it might be that other software (e.g., VPN) might be causing a timeout issue, as users noted in these two comments:
- https://github.com/tidyverse/googlesheets4/issues/187#issuecomment-692995404
- https://github.com/tidyverse/googledrive/issues/234#issuecomment-435379426
